Hexapod~Control: PID Class Reference
PID Class Reference
PID Class.
#include <PID.h>
Public Member Functions
PID ()
Default constructor for the class.
PID (double dt, double Kp, double Ki, double Kd)
Constructor for the class initialising dt, Kp, Ki and Kd.
PID (double dt)
Constructor for the class initialising dt.
~PID ()
Default destructor for the class.
void setParameters (double Kp, double Ki, double Kd)
void setKp (double kp)
void setKi (double ki)
void setKd (double kd)
void togglePID (bool state)
Toggle the PID controller on or off.
void reset ()
double getError ()
double calculate (double setpoint, double pv)
Calculates the output of the PID controller.
Public Attributes
double _dt = 0.05
The time interval of the controller.
double _Kp = 1.08
The proportional gain of the controller.
double _Ki = 2.2
The integral gain of the controller.
double _Kd = 0.027
The differential gain of the controller.
double _pre_error = 0
The error in the controller.
double _integral = 0
The cumulative integral of the controller.
bool enabled = false
The state of the controller.
Detailed Description
PID Class.
Definition at line 18 of file PID.h.
Constructor & Destructor Documentation
PID() [1/3]
PID::PID ()
Default constructor for the class.
Class constructor
Definition at line 24 of file PID.cpp.
PID() [2/3]
PID::PID (double dt, double Kp, double Ki, double Kd)
Constructor for the class initialising dt, Kp, Ki and Kd.
Class constructor
Parameters
dt The time interval of the controller.
Kp The proportional gain of the controller.
Ki The integral gain of the controller.
Kd The differential gain of the controller.
Implementation
Definition at line 13 of file PID.cpp.
References _dt, _Kd, _Ki, _Kp, and enabled.
PID() [3/3]
PID::PID (double dt)
Constructor for the class initialising dt.
Class constructor
Parameters
dt The time interval of the controller.
Definition at line 28 of file PID.cpp.
References _dt.
~PID()
PID::~PID ()
Default destructor for the class.
Class destructor cleans up memory by deleting pointers and lists.
Definition at line 32 of file PID.cpp.
Member Function Documentation
calculate()
double PID::calculate (double setpoint, double pv)
Calculates the output of the PID controller.
Parameters
setpoint The set point (command) value for the PID controller.
pv The value to compare the set point to (angle reading).
Returns
The output of the PID controller.
Definition at line 63 of file PID.cpp.
References _dt, _integral, _Kd, _Ki, _Kp, _pre_error, and enabled.
Referenced by HAL_UART_RxCpltCallback().
getError()
double PID::getError ()
Definition at line 92 of file PID.cpp.
References _pre_error.
reset()
void PID::reset ()
Definition at line 58 of file PID.cpp.
References _integral, and _pre_error.
Referenced by setKd(), setKi(), setKp(), and Hexapod::update().
setKd()
void PID::setKd (double kd)
Definition at line 52 of file PID.cpp.
References _Kd, and reset().
Referenced by HAL_UART_RxCpltCallback().
setKi()
void PID::setKi (double ki)
Definition at line 47 of file PID.cpp.
References _Ki, and reset().
Referenced by HAL_UART_RxCpltCallback().
setKp()
void PID::setKp (double kp)
Definition at line 42 of file PID.cpp.
References _Kp, and reset().
Referenced by HAL_UART_RxCpltCallback().
setParameters()
void PID::setParameters (double Kp, double Ki, double Kd)
Definition at line 36 of file PID.cpp.
References _Kd, _Ki, and _Kp.
togglePID()
void PID::togglePID (bool state)
Toggle the PID controller on or off.
Definition at line 96 of file PID.cpp.
References enabled.
Referenced by HAL_UART_RxCpltCallback(), and main().
Member Data Documentation
_dt
double PID::_dt = 0.05
The time interval of the controller.
Definition at line 22 of file PID.h.
Referenced by calculate(), and PID().
_integral
double PID::_integral = 0
The cumulative integral of the controller.
Definition at line 32 of file PID.h.
Referenced by calculate(), and reset().
_Kd
double PID::_Kd = 0.027
The differential gain of the controller.
Definition at line 28 of file PID.h.
Referenced by calculate(), PID(), setKd(), and setParameters().
_Ki
double PID::_Ki = 2.2
The integral gain of the controller.
Definition at line 26 of file PID.h.
Referenced by calculate(), PID(), setKi(), and setParameters().
_Kp
double PID::_Kp = 1.08
The proportional gain of the controller.
Definition at line 24 of file PID.h.
Referenced by calculate(), PID(), setKp(), and setParameters().
_pre_error
double PID::_pre_error = 0
The error in the controller.
Definition at line 30 of file PID.h.
Referenced by calculate(), getError(), and reset().
enabled
bool PID::enabled = false
The state of the controller.
Definition at line 35 of file PID.h.
Referenced by calculate(), HAL_UART_RxCpltCallback(), PID(), togglePID(), and Hexapod::update().
The documentation for this class was generated from the following files:
PID.h
PID.cpp