Hexapod~Control: Leg Class Reference
Leg Class Reference
Leg Class.
#include <Leg.h>
Public Member Functions
Leg (CommsManager *comms)
Default constructor for the class.
Leg (Motor m1, Motor m2, Motor m3, uint16_t rotation, double duty_offset, CommsManager *comms)
Constructor for the class initializing leg parameters.
Leg (uint8_t ID1, uint8_t ID2, uint8_t ID3, uint16_t rotation, double duty_offset, CommsManager *comms)
Constructor for the class initializing leg parameters.
~Leg (void)
Default destructor for the class.
void inverseKinematics (void)
Calculates the inverse kinematics of the leg.
double Lib_abs (double val)
Get the absolute value of a number.
Motor * getMotor (uint8_t ID)
Get the motor object corresponding to the motor ID.
void setTiltOffset (double tiltOffset)
void makePath (double radialDistance, double direction, double strideLength, double stepHeight, double bodyHeight, double slopePitch, double slopeRoll, double bodyRotation)
Generate the path for each leg for the Hexapod to walk.
void moveNextPathPoint (void)
Move the current goal position to the next point in the path.
void writeRegs (enum CONTROL_TABLE reg, uint8_t *data, uint8_t dataLength)
Writes one or more registers of all motors in the leg.
void setOffsets (double off1, double off2, double off3)
Sets the offset values of each motor in the leg.
void setPosition (double x, double y, double z)
Sets the position of the leg in cartesian coordinates.
void setPosition (double *xyz)
Sets the position of the leg in cartesian coordinates.
void setTheta (double theta1, double theta2, double theta3)
Sets the position of the leg from motor theta values.
void setTheta (double *theta)
Sets the position of the leg from motor theta values.
void setSpeed (double xd, double yd, double zd)
Sets the speed of each of the motors in the leg.
void setSpeedRPM (double th1d, double th2d, double th3d)
Sets the speed of each of the motors in the leg.
void setSpeed (double *theta_dot)
Sets the speed of each of the motors in the leg.
void setPositionBits (void)
Sets the position bytes of each of the motors in the leg.
void setPositionBits (uint16_t m1, uint16_t m2, uint16_t m3)
Sets the position bytes of each of the motors in the leg.
void setSpeedBits (void)
Sets the speed bytes of each of the motors in the leg.
void move ()
Moves the leg to the current goal position.
Public Attributes
double L1x = 53.17
The legs link 1 x dimension.
double L1z = 8.0
The legs link 1 z dimension.
double L2 = 101.88
The legs link 2 dimension.
double L3 = 149.16
The legs link 3 dimension.
const double bodyRadius = 125.54
The hexapod's body radius.
int rotation
The rotation of the leg relative to leg 1.
Point< double > * theta_dot = new Point<double>(0,0,0,THETA)
A point array containing the RPM of each motor in the leg.
Motor * motors [3]
A pointer to an array of motor objects.
Point< double > positionXYZ
A Point object containing the current XYZ position of the leg.
Point< double > positionTHETA
A Point object containing the current theta values of the motors of the leg.
uint currentPathPoint = 0
A counter holding the current position in the walking path.
Path * legPath = new Path()
A Path object holding the current path for the leg.
double dutyOffset = 0
The duty cycle offset of the leg relative to leg 1 of the hexapod.
double tiltOffset = 0
The tilt offset of the hexapod relative to its current position.
Private Member Functions
void forwardKinematics (void)
Calculate the forward kinematics of the leg.
void UARTWrite (uint8_t *data, uint8_t dataLength)
Write data to the UART channel of the leg.
Private Attributes
CommsManager * comms
A pointer to the global communications manager.
Point< double > offsets
A point array containing the default leg offsets.
double legRotation = 0
The rotation of the leg around the center of the Hexapod for body rotation.
Detailed Description
Leg Class.
Definition at line 25 of file Leg.h.
Constructor & Destructor Documentation
Leg() [1/3]
Leg::Leg (CommsManager * comms)
Default constructor for the class.
Class constructor
Definition at line 10 of file Leg.cpp.
References comms, motors, and rotation.
Leg() [2/3]
Leg::Leg (Motor m1, Motor m2, Motor m3, uint16_t rotation, double duty_offset, CommsManager * comms)
Constructor for the class initializing leg parameters.
Parameters
m1 The first motor in the leg.
m2 The second motor in the leg.
m3 The third motor in the leg.
rotation The rotation of the leg relative to leg 1 of the hexapod.
duty_offset The duty cycle offset when walking relative to leg 1 of the hexapod.
comms A pointer to the global communications manager.
Class constructor
Definition at line 18 of file Leg.cpp.
References comms, dutyOffset, motors, Point< T >::p1, Point< T >::p2, Point< T >::p3, positionTHETA, positionXYZ, rotation, and theta_dot.
Leg() [3/3]
Leg::Leg (uint8_t ID1, uint8_t ID2, uint8_t ID3, uint16_t rotation, double duty_offset, CommsManager * comms)
Constructor for the class initializing leg parameters.
Parameters
ID1 The ID number of the first motor in the leg.
ID2 The ID number of the second motor in the leg.
ID3 The ID number of the third motor in the leg.
rotation The rotation of the leg relative to leg 1 of the hexapod.
duty_offset The duty cycle offset when walking relative to leg 1 of the hexapod.
comms A pointer to the global communications manager.
Class constructor
Definition at line 43 of file Leg.cpp.
References comms, currentPathPoint, dutyOffset, legPath, motors, Point< T >::p1, Point< T >::p2, Point< T >::p3, Path::pathSize, positionTHETA, positionXYZ, rotation, and theta_dot.
~Leg()
Leg::~Leg (void)
Default destructor for the class.
Class destructor cleans up memory by deleting pointers and lists.
Definition at line 71 of file Leg.cpp.
Member Function Documentation
forwardKinematics()
void Leg::forwardKinematics (void) private
Calculate the forward kinematics of the leg.
Definition at line 268 of file Leg.cpp.
References bodyRadius, L1x, L1z, L2, L3, Point< T >::p1, Point< T >::p2, Point< T >::p3, positionTHETA, positionXYZ, and rotation.
Referenced by setPosition(), and setTheta().
getMotor()
Motor * Leg::getMotor (uint8_t ID)
Get the motor object corresponding to the motor ID.
Parameters
ID The ID of the motor to return.
Returns
A pointer to the motor object.
Definition at line 340 of file Leg.cpp.
References motors.
inverseKinematics()
void Leg::inverseKinematics (void)
Calculates the inverse kinematics of the leg.
Definition at line 240 of file Leg.cpp.
References bodyRadius, L1x, L1z, L2, L3, Point< T >::p1, Point< T >::p2, Point< T >::p3, positionTHETA, positionXYZ, rotation, and tiltOffset.
Referenced by Hexapod::setNextPathPoint(), setPosition(), and setTiltOffset().
Lib_abs()
double Leg::Lib_abs (double val)
Get the absolute value of a number.
Parameters
val The value to get the absolute of.
Returns
The absolute value.
Definition at line 121 of file Leg.cpp.
Referenced by setSpeed().
makePath()
void Leg::makePath (double radialDistance, double direction, double strideLength, double stepHeight, double bodyHeight, double slopePitch, double slopeRoll, double bodyRotation)
Generate the path for each leg for the Hexapod to walk.
Parameters
radialDistance The distance from the center of the Hexapod to the center of the support phase line.
direction The direction of the Hexapod .
strideLength The stride length of each leg.
stepHeight The step height of each leg.
bodyHeight The body height of the Hexapod.
slopePitch The pitch of the slope the Hexapod is walking on.
slopeRoll The roll of the slope the Hexapod is walking on.
Definition at line 334 of file Leg.cpp.
References legPath, legRotation, rotation, and Path::setPoints().
Referenced by Hexapod::makePath().
move()
void Leg::move ()
Moves the leg to the current goal position.
Definition at line 321 of file Leg.cpp.
References Motor::getGoalMovementBits(), GOAL_POSITION_L, motors, and writeRegs().
moveNextPathPoint()
void Leg::moveNextPathPoint (void)
Move the current goal position to the next point in the path.
setOffsets()
void Leg::setOffsets (double off1, double off2, double off3)
Sets the offset values of each motor in the leg.
Parameters
off1 The offset of the first motor in radians.
off2 The offset of the second motor in radians.
off3 The offset of the third motor in radians.
Definition at line 75 of file Leg.cpp.
References offsets, Point< T >::p1, Point< T >::p2, and Point< T >::p3.
Referenced by Hexapod::setLegOffsets().
setPosition() [1/2]
void Leg::setPosition (double x, double y, double z)
Sets the position of the leg in cartesian coordinates.
Parameters
x The x position of the foot tip.
y The y position of the foot tip.
z The z position of the foot tip.
Definition at line 81 of file Leg.cpp.
References inverseKinematics(), Point< T >::p1, Point< T >::p2, Point< T >::p3, positionXYZ, and setPositionBits().
Referenced by Hexapod::setPosition(), and Hexapod::turnBody().
setPosition() [2/2]
void Leg::setPosition (double * xyz)
Sets the position of the leg in cartesian coordinates.
Parameters
xyz A pointer to an array holding the goal x, y and z positions of the foot tip.
Definition at line 91 of file Leg.cpp.
References forwardKinematics(), inverseKinematics(), Point< T >::p1, Point< T >::p2, Point< T >::p3, positionXYZ, and setPositionBits().
setPositionBits() [1/2]
void Leg::setPositionBits (void)
Sets the position bytes of each of the motors in the leg.
Definition at line 219 of file Leg.cpp.
References Motor::calcPositionBits(), motors, Point< T >::p1, Point< T >::p2, Point< T >::p3, and positionTHETA.
Referenced by Hexapod::setNextPathPoint(), setPosition(), Hexapod::setPositionBits(), setTheta(), and setTiltOffset().
setPositionBits() [2/2]
void Leg::setPositionBits (uint16_t m1, uint16_t m2, uint16_t m3)
Sets the position bytes of each of the motors in the leg.
Parameters
m1 The 2 byte position data from 0 to 1023 of motor 1 in the leg.
m2 The 2 byte position data from 0 to 1023 of motor 2 in the leg.
m3 The 2 byte position data from 0 to 1023 of motor 3 in the leg.
setSpeed() [1/2]
void Leg::setSpeed (double xd, double yd, double zd)
Sets the speed of each of the motors in the leg.
Parameters
xd The speed of leg in the x direction in m/s.
yd The speed of leg in the y direction in m/s.
zd The speed of leg in the z direction in m/s.
Definition at line 129 of file Leg.cpp.
References L1x, L1z, L2, L3, Lib_abs(), Point< T >::p1, Point< T >::p2, Point< T >::p3, positionTHETA, rotation, setSpeedBits(), and theta_dot.
Referenced by Hexapod::setNextPathPoint(), and Hexapod::setSpeed().
setSpeed() [2/2]
void Leg::setSpeed (double * theta_dot)
Sets the speed of each of the motors in the leg.
Parameters
theta_dot A pointer to an array holding the goal speed values of each of the motors in the leg in RPM.
Definition at line 211 of file Leg.cpp.
References setSpeedBits().
setSpeedBits()
void Leg::setSpeedBits (void)
Sets the speed bytes of each of the motors in the leg.
Definition at line 225 of file Leg.cpp.
References Motor::calcSpeedBits(), motors, Point< T >::p1, Point< T >::p2, Point< T >::p3, and theta_dot.
Referenced by setSpeed(), and setSpeedRPM().
setSpeedRPM()
void Leg::setSpeedRPM (double th1d, double th2d, double th3d)
Sets the speed of each of the motors in the leg.
Parameters
th1d The speed of motor 1 in the leg in RPM.
th2d The speed of motor 2 in the leg in RPM.
th3d The speed of motor 3 in the leg in RPM.
Definition at line 203 of file Leg.cpp.
References Point< T >::p1, Point< T >::p2, Point< T >::p3, setSpeedBits(), and theta_dot.
Referenced by Hexapod::setSpeedRPM().
setTheta() [1/2]
void Leg::setTheta (double theta1, double theta2, double theta3)
Sets the position of the leg from motor theta values.
Parameters
theta1 The theta value of motor 1 in the leg.
theta2 The theta value of motor 2 in the leg.
theta3 The theta value of motor 3 in the leg.
Definition at line 102 of file Leg.cpp.
References forwardKinematics(), Point< T >::p1, Point< T >::p2, Point< T >::p3, positionTHETA, and setPositionBits().
Referenced by Hexapod::liftOntoBase(), Hexapod::turnBody(), and Hexapod::twistBody().
setTheta() [2/2]
void Leg::setTheta (double * theta)
Sets the position of the leg from motor theta values.
Parameters
theta A pointer to an array holding the goal theta values of each of the motors in the leg.
Definition at line 111 of file Leg.cpp.
References forwardKinematics(), Point< T >::p1, Point< T >::p2, Point< T >::p3, positionTHETA, and setPositionBits().
setTiltOffset()
void Leg::setTiltOffset (double tiltOffset)
Parameters
tiltOffset
Definition at line 231 of file Leg.cpp.
References inverseKinematics(), setPositionBits(), and tiltOffset.
Referenced by Hexapod::setPose().
UARTWrite()
void Leg::UARTWrite (uint8_t * data, uint8_t dataLength) private
Write data to the UART channel of the leg.
Parameters
data A pointer to the data to write.
dataLength The length of the data to write.
Definition at line 344 of file Leg.cpp.
References comms, DMA, CommsManager::getMotorUART(), and CommsManager::transmitMotors().
Referenced by writeRegs().
writeRegs()
void Leg::writeRegs (enum CONTROL_TABLE reg, uint8_t * data, uint8_t dataLength)
Writes one or more registers of all motors in the leg.
Parameters
reg The register to begin writing to.
data A pointer to the data to write.
dataLength The length of data to write.
Definition at line 291 of file Leg.cpp.
References Motor::ID, motors, SYNC_WRITE, and UARTWrite().
Referenced by move().
Member Data Documentation
bodyRadius
const double Leg::bodyRadius = 125.54
The hexapod's body radius.
Definition at line 65 of file Leg.h.
Referenced by forwardKinematics(), inverseKinematics(), and Hexapod::reachablePosition().
comms
CommsManager* Leg::comms private
A pointer to the global communications manager.
Definition at line 29 of file Leg.h.
Referenced by Leg(), and UARTWrite().
currentPathPoint
uint Leg::currentPathPoint = 0
A counter holding the current position in the walking path.
Definition at line 80 of file Leg.h.
Referenced by Leg(), and Hexapod::setNextPathPoint().
dutyOffset
double Leg::dutyOffset = 0
The duty cycle offset of the leg relative to leg 1 of the hexapod.
Definition at line 85 of file Leg.h.
Referenced by Leg().
L1x
double Leg::L1x = 53.17
The legs link 1 x dimension.
Definition at line 57 of file Leg.h.
Referenced by forwardKinematics(), inverseKinematics(), Hexapod::reachablePosition(), and setSpeed().
L1z
double Leg::L1z = 8.0
The legs link 1 z dimension.
Definition at line 59 of file Leg.h.
Referenced by forwardKinematics(), inverseKinematics(), Hexapod::reachablePosition(), and setSpeed().
L2
double Leg::L2 = 101.88
The legs link 2 dimension.
Definition at line 61 of file Leg.h.
Referenced by forwardKinematics(), inverseKinematics(), Hexapod::reachablePosition(), and setSpeed().
L3
double Leg::L3 = 149.16
The legs link 3 dimension.
Definition at line 63 of file Leg.h.
Referenced by forwardKinematics(), inverseKinematics(), Hexapod::reachablePosition(), and setSpeed().
legPath
Path* Leg::legPath = new Path()
A Path object holding the current path for the leg.
Definition at line 82 of file Leg.h.
Referenced by Hexapod::Initialise(), Leg(), makePath(), Hexapod::setNextPathPoint(), and Hexapod::update().
legRotation
double Leg::legRotation = 0 private
The rotation of the leg around the center of the Hexapod for body rotation.
Definition at line 36 of file Leg.h.
Referenced by makePath().
motors
Motor* Leg::motors[3]
A pointer to an array of motor objects.
Definition at line 74 of file Leg.h.
Referenced by getMotor(), Hexapod::getMotor(), Leg(), move(), Hexapod::move(), Hexapod::readAllMotors(), setPositionBits(), setSpeedBits(), Hexapod::writeRegAll(), and writeRegs().
offsets
Point<double> Leg::offsets private
A point array containing the default leg offsets.
Definition at line 31 of file Leg.h.
Referenced by setOffsets().
positionTHETA
Point<double> Leg::positionTHETA
A Point object containing the current theta values of the motors of the leg.
Definition at line 78 of file Leg.h.
Referenced by forwardKinematics(), inverseKinematics(), Leg(), Hexapod::reachablePosition(), setPositionBits(), setSpeed(), setTheta(), Hexapod::turnBody(), and Hexapod::twistBody().
positionXYZ
Point<double> Leg::positionXYZ
A Point object containing the current XYZ position of the leg.
Definition at line 76 of file Leg.h.
Referenced by forwardKinematics(), inverseKinematics(), Leg(), Hexapod::reachablePosition(), Hexapod::setNextPathPoint(), setPosition(), Hexapod::turnBody(), and Hexapod::update().
rotation
int Leg::rotation
The rotation of the leg relative to leg 1.
Definition at line 68 of file Leg.h.
Referenced by forwardKinematics(), inverseKinematics(), Leg(), makePath(), and setSpeed().
theta_dot
Point<double>* Leg::theta_dot = new Point<double>(0,0,0,THETA)
A point array containing the RPM of each motor in the leg.
Definition at line 71 of file Leg.h.
Referenced by Leg(), setSpeed(), setSpeedBits(), and setSpeedRPM().
tiltOffset
double Leg::tiltOffset = 0
The tilt offset of the hexapod relative to its current position.
Definition at line 88 of file Leg.h.
Referenced by inverseKinematics(), and setTiltOffset().
The documentation for this class was generated from the following files:
Leg.h
Leg.cpp