Hexapod~Control: CommsManager Class Reference
CommsManager Class Reference
Communications Manager object.
#include <CommsManager.h>
Public Member Functions
CommsManager (void)
Default constructor for the class.
~CommsManager (void)
Default destructor for the class.
void UART_init (void)
Initialise the UART modules.
void setRemoteBaud (uint32_t BAUD)
Sets the remote baud rate.
void DMA_init (void)
Initialise the DMA modules.
UART_HandleTypeDef * getMotorUART ()
Get the UART struct for the motors (UART1).
UART_HandleTypeDef * getRemoteUART ()
Get the UART struct for the remote (UART2).
UART_HandleTypeDef * getAccUART ()
Get the UART struct for the IMU (UART3).
DMA_HandleTypeDef * getMotorDMA (COMM_DIR tx_rx)
Get the DMA struct for the motors (DMA2 TX/RX).
DMA_HandleTypeDef * getRemoteDMA (COMM_DIR tx_rx)
Get the DMA struct for the remote (DMA1 TX/RX).
DMA_HandleTypeDef * getAccDMA (COMM_DIR tx_rx)
Get the DMA struct for the IMU (DMA1 TX/RX).
HAL_StatusTypeDef transmitMotors (uint8_t *data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Transmit data to the motors.
HAL_StatusTypeDef transmitRemote (uint8_t *data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Transmit data to the remote.
HAL_StatusTypeDef transmitAcc (uint8_t *data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Transmit data to the IMU.
HAL_StatusTypeDef receiveMotors (uint8_t *data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Receive data from the motors.
HAL_StatusTypeDef receiveRemote (uint8_t *data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Receive data from the remote.
HAL_StatusTypeDef receiveAcc (uint8_t *data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Receive data from the IMU.
Public Attributes
uint8_t remoteFailureCount = 0
Counter to hold the number of failed remote connections.
Private Attributes
UART_HandleTypeDef UART1_HandleStructure
HAL library UART1 initialization structure.
UART_HandleTypeDef UART2_HandleStructure
HAL library UART2 initialization structure.
UART_HandleTypeDef UART3_HandleStructure
HAL library UART3 initialization structure.
DMA_HandleTypeDef DMA2_HandleStructure_UART1_TX
HAL library DMA2 TX (UART1) initialization structure.
DMA_HandleTypeDef DMA2_HandleStructure_UART1_RX
HAL library DMA2 RX (UART1) initialization structure.
DMA_HandleTypeDef DMA1_HandleStructure_UART2_TX
HAL library DMA1 TX (UART2) initialization structure.
DMA_HandleTypeDef DMA1_HandleStructure_UART2_RX
HAL library DMA1 RX (UART2) initialization structure.
DMA_HandleTypeDef DMA1_HandleStructure_UART3_RX
HAL library DMA1 TX (UART3) initialization structure.
DMA_HandleTypeDef DMA1_HandleStructure_UART3_TX
HAL library DMA1 RX (UART3) initialization structure.
Detailed Description
Communications Manager object.
Manages all communications initialisations and transmission and reception of data.
Definition at line 20 of file CommsManager.h.
Constructor & Destructor Documentation
CommsManager()
CommsManager::CommsManager (void)
Default constructor for the class.
Class constructor.
Definition at line 12 of file CommsManager.cpp.
References DMA1_HandleStructure_UART2_RX, DMA1_HandleStructure_UART2_TX, DMA1_HandleStructure_UART3_RX, DMA1_HandleStructure_UART3_TX, DMA2_HandleStructure_UART1_RX, DMA2_HandleStructure_UART1_TX, UART1_HandleStructure, UART2_HandleStructure, and UART3_HandleStructure.
~CommsManager()
CommsManager::~CommsManager (void)
Default destructor for the class.
Class destructor cleans up memory by deleting pointers and lists.
Definition at line 27 of file CommsManager.cpp.
Member Function Documentation
DMA_init()
void CommsManager::DMA_init (void)
Initialise the DMA modules.
Definition at line 82 of file CommsManager.cpp.
References DMA1_HandleStructure_UART2_RX, DMA1_HandleStructure_UART2_TX, DMA1_HandleStructure_UART3_RX, DMA1_HandleStructure_UART3_TX, DMA2_HandleStructure_UART1_RX, DMA2_HandleStructure_UART1_TX, UART1_HandleStructure, UART2_HandleStructure, and UART3_HandleStructure.
Referenced by Hexapod::Initialise().
getAccDMA()
DMA_HandleTypeDef * CommsManager::getAccDMA (COMM_DIR tx_rx)
Get the DMA struct for the IMU (DMA1 TX/RX).
Parameters
tx_rx COMM_DIR enum specifying the DMA struct to return.
Returns
A pointer to the IMU DMA struct.
Definition at line 222 of file CommsManager.cpp.
References DMA1_HandleStructure_UART3_RX, DMA1_HandleStructure_UART3_TX, RX, and TX.
Referenced by DMA1_Stream1_IRQHandler(), and DMA1_Stream3_IRQHandler().
getAccUART()
UART_HandleTypeDef * CommsManager::getAccUART ()
Get the UART struct for the IMU (UART3).
Returns
A pointer to the IMU UART struct.
Definition at line 198 of file CommsManager.cpp.
References UART3_HandleStructure.
Referenced by Accelerometer::requestAccelData(), Accelerometer::resetHeading(), Accelerometer::setConfigMode(), Accelerometer::setMeasurementMode(), and USART3_IRQHandler().
getMotorDMA()
DMA_HandleTypeDef * CommsManager::getMotorDMA (COMM_DIR tx_rx)
Get the DMA struct for the motors (DMA2 TX/RX).
Parameters
tx_rx COMM_DIR enum specifying the DMA struct to return.
Returns
A pointer to the motor DMA struct.
Definition at line 202 of file CommsManager.cpp.
References DMA2_HandleStructure_UART1_RX, DMA2_HandleStructure_UART1_TX, RX, and TX.
Referenced by DMA2_Stream2_IRQHandler(), and DMA2_Stream7_IRQHandler().
getMotorUART()
UART_HandleTypeDef * CommsManager::getMotorUART ()
Get the UART struct for the motors (UART1).
Returns
A pointer to the motor UART struct.
Definition at line 190 of file CommsManager.cpp.
References UART1_HandleStructure.
Referenced by Hexapod::enterLowPowerMode(), Motor::readReg(), Leg::UARTWrite(), and USART1_IRQHandler().
getRemoteDMA()
DMA_HandleTypeDef * CommsManager::getRemoteDMA (COMM_DIR tx_rx)
Get the DMA struct for the remote (DMA1 TX/RX).
Parameters
tx_rx COMM_DIR enum specifying the DMA struct to return.
Returns
A pointer to the remote DMA struct.
Definition at line 212 of file CommsManager.cpp.
References DMA1_HandleStructure_UART2_RX, DMA1_HandleStructure_UART2_TX, RX, and TX.
Referenced by DMA1_Stream5_IRQHandler(), and DMA1_Stream6_IRQHandler().
getRemoteUART()
UART_HandleTypeDef * CommsManager::getRemoteUART ()
Get the UART struct for the remote (UART2).
Returns
A pointer to the remote UART struct.
Definition at line 194 of file CommsManager.cpp.
References UART2_HandleStructure.
Referenced by Remote::sendAcc(), and USART2_IRQHandler().
receiveAcc()
HAL_StatusTypeDef CommsManager::receiveAcc (uint8_t * data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Receive data from the IMU.
Parameters
data Pointer to the data array to receive.
size Size of the data array to receive.
timeout Timeout for blocking reception.
type Type of reception (DMA, INTERRUPT, BLOCKING).
Returns
True or false as success or failure of reception.
Definition at line 313 of file CommsManager.cpp.
References BLOCKING, DMA, INTERRUPT, and UART3_HandleStructure.
Referenced by Accelerometer::receiveAccelData().
receiveMotors()
HAL_StatusTypeDef CommsManager::receiveMotors (uint8_t * data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Receive data from the motors.
Parameters
data Pointer to the data array to receive.
size Size of the data array to receive.
timeout Timeout for blocking reception.
type Type of reception (DMA, INTERRUPT, BLOCKING).
Returns
True or false as success or failure of reception.
Definition at line 281 of file CommsManager.cpp.
References BLOCKING, DMA, INTERRUPT, and UART1_HandleStructure.
Referenced by Motor::pingBool(), Motor::pingData(), Motor::readReg(), and Motor::readTable().
receiveRemote()
HAL_StatusTypeDef CommsManager::receiveRemote (uint8_t * data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Receive data from the remote.
Parameters
data Pointer to the data array to receive.
size Size of the data array to receive.
timeout Timeout for blocking reception.
type Type of reception (DMA, INTERRUPT, BLOCKING).
Returns
True or false as success or failure of reception.
Definition at line 297 of file CommsManager.cpp.
References BLOCKING, DMA, INTERRUPT, and UART2_HandleStructure.
Referenced by Hexapod::checkRemoteConfig(), Remote::receiveRemoteData(), and Hexapod::setRemoteConfig().
setRemoteBaud()
void CommsManager::setRemoteBaud (uint32_t BAUD)
Sets the remote baud rate.
Definition at line 31 of file CommsManager.cpp.
References UART2_HandleStructure.
Referenced by Hexapod::setRemoteConfig().
transmitAcc()
HAL_StatusTypeDef CommsManager::transmitAcc (uint8_t * data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Transmit data to the IMU.
Parameters
data Pointer to the data array to transmit.
size Size of the data array to transmit.
timeout Timeout for blocking transmissions.
type Type of transmission (DMA, INTERRUPT, BLOCKING).
Returns
True or false as success or failure of transmission.
Definition at line 265 of file CommsManager.cpp.
References BLOCKING, DMA, INTERRUPT, and UART3_HandleStructure.
Referenced by Accelerometer::requestAccelData(), Accelerometer::resetHeading(), Accelerometer::setConfigMode(), and Accelerometer::setMeasurementMode().
transmitMotors()
HAL_StatusTypeDef CommsManager::transmitMotors (uint8_t * data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Transmit data to the motors.
Parameters
data Pointer to the data array to transmit.
size Size of the data array to transmit.
timeout Timeout for blocking transmissions.
type Type of transmission (DMA, INTERRUPT, BLOCKING).
Returns
True or false as success or failure of transmission.
Definition at line 232 of file CommsManager.cpp.
References BLOCKING, DMA, INTERRUPT, and UART1_HandleStructure.
Referenced by Hexapod::move(), Motor::pingBool(), Motor::pingData(), Motor::readReg(), Motor::readTable(), Leg::UARTWrite(), and Motor::writeReg().
transmitRemote()
HAL_StatusTypeDef CommsManager::transmitRemote (uint8_t * data, uint8_t size, uint16_t timeout, enum UART_TRANSMISSION_TYPE type)
Transmit data to the remote.
Parameters
data Pointer to the data array to transmit.
size Size of the data array to transmit.
timeout Timeout for blocking transmissions.
type Type of transmission (DMA, INTERRUPT, BLOCKING).
Returns
True or false as success or failure of transmission.
Definition at line 251 of file CommsManager.cpp.
References BLOCKING, DMA, INTERRUPT, and UART2_HandleStructure.
Referenced by Hexapod::checkRemoteConfig(), Remote::processRemoteData(), Remote::sendAcc(), Remote::sendASCII(), Remote::sendCharging(), Remote::sendError(), Hexapod::setRemoteConfig(), Hexapod::startCharging(), Hexapod::stopCharging(), and TIM3_IRQHandler().
UART_init()
void CommsManager::UART_init (void)
Initialise the UART modules.
Definition at line 37 of file CommsManager.cpp.
References UART1, UART1_HandleStructure, UART2, UART2_HandleStructure, UART3, and UART3_HandleStructure.
Referenced by Hexapod::Initialise().
Member Data Documentation
DMA1_HandleStructure_UART2_RX
DMA_HandleTypeDef CommsManager::DMA1_HandleStructure_UART2_RX private
HAL library DMA1 RX (UART2) initialization structure.
Definition at line 38 of file CommsManager.h.
Referenced by CommsManager(), DMA_init(), and getRemoteDMA().
DMA1_HandleStructure_UART2_TX
DMA_HandleTypeDef CommsManager::DMA1_HandleStructure_UART2_TX private
HAL library DMA1 TX (UART2) initialization structure.
Definition at line 36 of file CommsManager.h.
Referenced by CommsManager(), DMA_init(), and getRemoteDMA().
DMA1_HandleStructure_UART3_RX
DMA_HandleTypeDef CommsManager::DMA1_HandleStructure_UART3_RX private
HAL library DMA1 TX (UART3) initialization structure.
Definition at line 41 of file CommsManager.h.
Referenced by CommsManager(), DMA_init(), and getAccDMA().
DMA1_HandleStructure_UART3_TX
DMA_HandleTypeDef CommsManager::DMA1_HandleStructure_UART3_TX private
HAL library DMA1 RX (UART3) initialization structure.
Definition at line 43 of file CommsManager.h.
Referenced by CommsManager(), DMA_init(), and getAccDMA().
DMA2_HandleStructure_UART1_RX
DMA_HandleTypeDef CommsManager::DMA2_HandleStructure_UART1_RX private
HAL library DMA2 RX (UART1) initialization structure.
Definition at line 33 of file CommsManager.h.
Referenced by CommsManager(), DMA_init(), and getMotorDMA().
DMA2_HandleStructure_UART1_TX
DMA_HandleTypeDef CommsManager::DMA2_HandleStructure_UART1_TX private
HAL library DMA2 TX (UART1) initialization structure.
Definition at line 31 of file CommsManager.h.
Referenced by CommsManager(), DMA_init(), and getMotorDMA().
remoteFailureCount
uint8_t CommsManager::remoteFailureCount = 0
Counter to hold the number of failed remote connections.
Definition at line 48 of file CommsManager.h.
Referenced by TIM3_IRQHandler().
UART1_HandleStructure
UART_HandleTypeDef CommsManager::UART1_HandleStructure private
HAL library UART1 initialization structure.
Definition at line 24 of file CommsManager.h.
Referenced by CommsManager(), DMA_init(), getMotorUART(), receiveMotors(), transmitMotors(), and UART_init().
UART2_HandleStructure
UART_HandleTypeDef CommsManager::UART2_HandleStructure private
HAL library UART2 initialization structure.
Definition at line 26 of file CommsManager.h.
Referenced by CommsManager(), DMA_init(), getRemoteUART(), receiveRemote(), setRemoteBaud(), transmitRemote(), and UART_init().
UART3_HandleStructure
UART_HandleTypeDef CommsManager::UART3_HandleStructure private
HAL library UART3 initialization structure.
Definition at line 28 of file CommsManager.h.
Referenced by CommsManager(), DMA_init(), getAccUART(), receiveAcc(), transmitAcc(), and UART_init().
The documentation for this class was generated from the following files:
CommsManager.h
CommsManager.cpp