Hexapod~Control: Remote Class Reference
Remote Class Reference
Class for sending data to and receiving data from the remote control.
#include <Remote.h>
Public Member Functions
Remote (CommsManager *comms)
Default constructor for the class.
~Remote (void)
Default destructor for the class.
void sendASCII (char *msg)
Send an ASCII string through the remote.
void sendCharging (bool charging)
Send the start or stop charging command to the charging base.
bool sendAcc (double pitch, double roll, double yaw, uint16_t timestamp, double slopePitch, double slopeRoll)
Send the IMU data through the remote.
void sendError (uint8_t errorLoc, uint8_t errorCode)
Send error data through the remote.
void receiveRemoteData (uint8_t size)
Receive the remote data using DMA.
bool isChecksumValid (void)
Check if the checksum sent by the remote control is valid.
void processRemoteData (void)
Process the remote data.
void floatToBytes (float value, uint8_t *bytes)
Convert a float into a byte array.
float bytesToFloat (uint8_t *bytes)
Convert a byte array into a float.
bool successfulPing (void)
Return the pingSuccess boolean.
Public Attributes
bool newData = false
A boolean trigger that will be true when new data is available.
double speed = 0
The speed data received from the remote.
double direction = 0
The direction data received from the remote.
double bodyHeight = 0
The body height data received from the remote.
uint8_t function = 0
The button function data received from the remote.
double twistBody = 0
The twist angle of the body.
bool sending = false
A state variable to determine if the remote is currently sending data.
bool pingSuccess = false
Boolean holding the status of the last ping.
bool charging = false
Boolean holding the current charging status.
Private Attributes
CommsManager * comms
A pointer to the global communications manager object.
uint8_t dma_dataPacket [10]
An array to hold the incoming remote data.
uint8_t dma_acc_transmit [26]
An array to hold the IMU data to transmit.
uint8_t dma_error_transmit [4]
An array to hold the error data to transmit.
Detailed Description
Class for sending data to and receiving data from the remote control.
Definition at line 26 of file Remote.h.
Constructor & Destructor Documentation
Remote()
Remote::Remote (CommsManager * comms)
Default constructor for the class.
Class constructor initializing the accelerometer remote_uart pointer.
Parameters
comms A pointer to the global communications manager object.
Definition at line 10 of file Remote.cpp.
References comms.
~Remote()
Remote::~Remote (void)
Default destructor for the class.
Class destructor cleans up memory by deleting pointers and lists.
Definition at line 15 of file Remote.cpp.
Member Function Documentation
bytesToFloat()
float Remote::bytesToFloat (uint8_t * bytes)
Convert a byte array into a float.
Parameters
bytes The byte array to convert.
Definition at line 182 of file Remote.cpp.
Referenced by HAL_UART_RxCpltCallback().
floatToBytes()
void Remote::floatToBytes (float value, uint8_t * bytes)
Convert a float into a byte array.
Parameters
value The float to convert.
bytes A pointer to the array to populate with the bytes.
Definition at line 178 of file Remote.cpp.
Referenced by sendAcc(), and TIM3_IRQHandler().
isChecksumValid()
bool Remote::isChecksumValid (void)
Check if the checksum sent by the remote control is valid.
Returns
True or false whether or not the checksum is valid.
Definition at line 163 of file Remote.cpp.
References dma_dataPacket.
Referenced by processRemoteData().
processRemoteData()
void Remote::processRemoteData (void)
Process the remote data.
Definition at line 86 of file Remote.cpp.
References bodyHeight, comms, direction, DMA, dma_dataPacket, isChecksumValid(), newData, speed, CommsManager::transmitRemote(), and twistBody.
Referenced by HAL_UART_RxCpltCallback().
receiveRemoteData()
void Remote::receiveRemoteData (uint8_t size)
Receive the remote data using DMA.
Definition at line 82 of file Remote.cpp.
References comms, DMA, dma_dataPacket, and CommsManager::receiveRemote().
Referenced by HAL_UART_ErrorCallback(), and Hexapod::Initialise().
sendAcc()
bool Remote::sendAcc (double pitch, double roll, double yaw, uint16_t timestamp, double slopePitch, double slopeRoll)
Send the IMU data through the remote.
Parameters
pitch The pitch of the IMU.
roll The roll of the IMU.
yaw The yaw of the IMU.
timestamp The timestamp of the IMU.
slopePitch The slope pitch of the Hexapod.
slopeRoll The slope roll of the Hexapod.
Definition at line 38 of file Remote.cpp.
References comms, DMA, dma_acc_transmit, floatToBytes(), CommsManager::getRemoteUART(), sending, and CommsManager::transmitRemote().
Referenced by TIM3_IRQHandler().
sendASCII()
void Remote::sendASCII (char * msg)
Send an ASCII string through the remote.
Parameters
msg A pointer to the char array to send.
Definition at line 19 of file Remote.cpp.
References comms, DMA, and CommsManager::transmitRemote().
Referenced by Hexapod::move(), and TIM3_IRQHandler().
sendCharging()
void Remote::sendCharging (bool charging)
Send the start or stop charging command to the charging base.
Parameters
charging True or false to start or stop charging respectively.
Definition at line 68 of file Remote.cpp.
References comms, DMA, and CommsManager::transmitRemote().
sendError()
void Remote::sendError (uint8_t errorLoc, uint8_t errorCode)
Send error data through the remote.
Parameters
errorLoc The location of the error (UART1, UART2, UART3)
errorCode The error code (Frame error, parity error etc...)
Definition at line 73 of file Remote.cpp.
References comms, DMA, dma_error_transmit, and CommsManager::transmitRemote().
Referenced by HAL_UART_ErrorCallback(), and Hexapod::PingAll().
successfulPing()
bool Remote::successfulPing (void)
Return the pingSuccess boolean.
Definition at line 187 of file Remote.cpp.
References pingSuccess.
Member Data Documentation
bodyHeight
double Remote::bodyHeight = 0
The body height data received from the remote.
Definition at line 49 of file Remote.h.
Referenced by processRemoteData(), and Hexapod::update().
charging
bool Remote::charging = false
Boolean holding the current charging status.
Definition at line 62 of file Remote.h.
Referenced by Hexapod::update().
comms
CommsManager* Remote::comms private
A pointer to the global communications manager object.
Definition at line 30 of file Remote.h.
Referenced by processRemoteData(), receiveRemoteData(), Remote(), sendAcc(), sendASCII(), sendCharging(), and sendError().
direction
double Remote::direction = 0
The direction data received from the remote.
Definition at line 47 of file Remote.h.
Referenced by processRemoteData(), and Hexapod::update().
dma_acc_transmit
uint8_t Remote::dma_acc_transmit[26] private
An array to hold the IMU data to transmit.
Definition at line 36 of file Remote.h.
Referenced by sendAcc().
dma_dataPacket
uint8_t Remote::dma_dataPacket[10] private
An array to hold the incoming remote data.
Definition at line 33 of file Remote.h.
Referenced by isChecksumValid(), processRemoteData(), and receiveRemoteData().
dma_error_transmit
uint8_t Remote::dma_error_transmit[4] private
An array to hold the error data to transmit.
Definition at line 39 of file Remote.h.
Referenced by sendError().
function
uint8_t Remote::function = 0
The button function data received from the remote.
Definition at line 51 of file Remote.h.
Referenced by Hexapod::update().
newData
bool Remote::newData = false
A boolean trigger that will be true when new data is available.
Definition at line 43 of file Remote.h.
Referenced by processRemoteData(), and Hexapod::update().
pingSuccess
bool Remote::pingSuccess = false
Boolean holding the status of the last ping.
Definition at line 59 of file Remote.h.
Referenced by HAL_UART_RxCpltCallback(), successfulPing(), and TIM3_IRQHandler().
sending
bool Remote::sending = false
A state variable to determine if the remote is currently sending data.
Definition at line 56 of file Remote.h.
Referenced by HAL_UART_ErrorCallback(), sendAcc(), and TIM3_IRQHandler().
speed
double Remote::speed = 0
The speed data received from the remote.
Definition at line 45 of file Remote.h.
Referenced by processRemoteData(), and Hexapod::update().
twistBody
double Remote::twistBody = 0
The twist angle of the body.
Definition at line 53 of file Remote.h.
Referenced by processRemoteData(), and Hexapod::update().
The documentation for this class was generated from the following files:
Remote.h
Remote.cpp