Hexapod~Control: main.cpp File Reference
main.cpp File Reference
main function
#include "CommsManager.h"
#include "Hexapod.h"
Functions
void main ()
void TIM2_IRQHandler (void)
Timer 2 interrupt for path position control.
void TIM3_IRQHandler (void)
Timer 3 interrupt for IMU and ADC reading.
void HAL_UART_TxCpltCallback (UART_HandleTypeDef *UART_HandleStructure)
UART transmit complete interrupt.
void HAL_UART_RxCpltCallback (UART_HandleTypeDef *UART_HandleStructure)
UART receive complete interrupt.
void HAL_UART_ErrorCallback (UART_HandleTypeDef *UART_HandleStructure)
UART Error Handler.
void USART1_IRQHandler (void)
UART1 (Motor) Handler.
void USART2_IRQHandler (void)
UART2 (Remote) Handler.
void USART3_IRQHandler (void)
UART3 (IMU) Handler.
void DMA2_Stream7_IRQHandler (void)
Motor (UART1) TX DMA Handler.
void DMA2_Stream2_IRQHandler (void)
Motor (UART1) RX DMA Handler.
void DMA1_Stream6_IRQHandler (void)
Remote (UART2) TX DMA Handler.
void DMA1_Stream5_IRQHandler (void)
Remote (UART2) RX DMA Handler.
void DMA1_Stream3_IRQHandler (void)
IMU (UART3) TX DMA Handler.
void DMA1_Stream1_IRQHandler (void)
IMU (UART3) RX DMA Handler.
void SysTick_Handler (void)
Systick Handler.
Variables
Hexapod HEX
Main Hexapod object.
Detailed Description
main function
Author
Ross Christopher (CHRROS005)
Date
Definition in file main.cpp.
Function Documentation
DMA1_Stream1_IRQHandler()
void DMA1_Stream1_IRQHandler (void)
IMU (UART3) RX DMA Handler.
Definition at line 587 of file main.cpp.
References Hexapod::comms, CommsManager::getAccDMA(), and RX.
DMA1_Stream3_IRQHandler()
void DMA1_Stream3_IRQHandler (void)
IMU (UART3) TX DMA Handler.
Definition at line 579 of file main.cpp.
References Hexapod::comms, CommsManager::getAccDMA(), and TX.
DMA1_Stream5_IRQHandler()
void DMA1_Stream5_IRQHandler (void)
Remote (UART2) RX DMA Handler.
Definition at line 571 of file main.cpp.
References Hexapod::comms, CommsManager::getRemoteDMA(), and RX.
DMA1_Stream6_IRQHandler()
void DMA1_Stream6_IRQHandler (void)
Remote (UART2) TX DMA Handler.
Definition at line 562 of file main.cpp.
References Hexapod::comms, CommsManager::getRemoteDMA(), and TX.
DMA2_Stream2_IRQHandler()
void DMA2_Stream2_IRQHandler (void)
Motor (UART1) RX DMA Handler.
Definition at line 554 of file main.cpp.
References Hexapod::comms, CommsManager::getMotorDMA(), and RX.
DMA2_Stream7_IRQHandler()
void DMA2_Stream7_IRQHandler (void)
Motor (UART1) TX DMA Handler.
DMA INTERRUPTS (Runs before read/write)
Definition at line 546 of file main.cpp.
References Hexapod::comms, CommsManager::getMotorDMA(), and TX.
HAL_UART_ErrorCallback()
void HAL_UART_ErrorCallback (UART_HandleTypeDef * UART_HandleStructure)
UART Error Handler.
Parameters
UART_HandleStructure Pointer to the UART struct which caused the error interrupt.
Definition at line 439 of file main.cpp.
References Hexapod::direction, Hexapod::lowPowerMode, Hexapod::newPosition, Remote::receiveRemoteData(), Hexapod::remote, Remote::sendError(), Remote::sending, UART1, UART2, and UART3.
HAL_UART_RxCpltCallback()
void HAL_UART_RxCpltCallback (UART_HandleTypeDef * UART_HandleStructure)
UART receive complete interrupt.
Parameters
UART_HandleStructure Pointer to the UART struct which caused the error interrupt.
Definition at line 287 of file main.cpp.
References Hexapod::accel, Remote::bytesToFloat(), PID::calculate(), Hexapod::direction, Hexapod::disableMotors(), PID::enabled, Hexapod::enableMotors(), Hexapod::IMUTransFreq, Hexapod::liftedForBase, Hexapod::newPosition, Hexapod::pidPitch, Hexapod::pidRoll, Remote::pingSuccess, Accelerometer::pitch, Hexapod::pitchSetPoint, Accelerometer::processAccelData(), Remote::processRemoteData(), Hexapod::remote, Accelerometer::roll, Hexapod::rollSetPoint, PID::setKd(), PID::setKi(), PID::setKp(), Hexapod::setPose(), Hexapod::shouldCharging, Hexapod::startCharging(), Hexapod::stopCharging(), PID::togglePID(), UART1, UART2, UART3, and Hexapod::update().
HAL_UART_TxCpltCallback()
void HAL_UART_TxCpltCallback (UART_HandleTypeDef * UART_HandleStructure)
UART transmit complete interrupt.
Parameters
UART_HandleStructure Pointer to the UART struct which caused the error interrupt.
Definition at line 262 of file main.cpp.
References UART1, UART2, and UART3.
main()
void main ()
Definition at line 22 of file main.cpp.
References Hexapod::charging, Hexapod::direction, DMA, Hexapod::Initialise(), Hexapod::lowPowerMode, Hexapod::move(), Hexapod::newPosition, Hexapod::pidPitch, Hexapod::pidRoll, Hexapod::pidYaw, Hexapod::setNextPathPoint(), Hexapod::stand(), Hexapod::startTimers(), Hexapod::timersReady, and PID::togglePID().
SysTick_Handler()
void SysTick_Handler (void)
Systick Handler.
Definition at line 596 of file main.cpp.
TIM2_IRQHandler()
void TIM2_IRQHandler (void)
Timer 2 interrupt for path position control.
Definition at line 124 of file main.cpp.
References Hexapod::charging, Hexapod::direction, Hexapod::getTIM(), Hexapod::newPosition, and Hexapod::timersReady.
TIM3_IRQHandler()
void TIM3_IRQHandler (void)
Timer 3 interrupt for IMU and ADC reading.
Definition at line 138 of file main.cpp.
References Hexapod::accel, Hexapod::charging, CHARGING_CC, CHARGING_CV, Hexapod::comms, Hexapod::disableMotors(), DMA, Hexapod::enterLowPowerMode(), Hexapod::exitLowPowerMode(), FAULT, Remote::floatToBytes(), Hexapod::getTIM(), Hexapod::IMUTransFreq, Hexapod::lowBatteryCount, Hexapod::lowPowerMode, NOT_CHARGING, Remote::pingSuccess, Accelerometer::pitch, Hexapod::readCharger(), Hexapod::remote, CommsManager::remoteFailureCount, Accelerometer::requestAccelData(), Accelerometer::roll, Remote::sendAcc(), Remote::sendASCII(), Remote::sending, Hexapod::shouldCharging, Hexapod::slopePitch, Hexapod::slopeRoll, Hexapod::startCharging(), CHARGER::status, Hexapod::stop(), Hexapod::TIM3Counter, Hexapod::timersReady, Accelerometer::timestamp, CommsManager::transmitRemote(), CHARGER::voltage, and Accelerometer::yaw.
USART1_IRQHandler()
void USART1_IRQHandler (void)
UART1 (Motor) Handler.
UNUSED IN DMA MODE, but needed or else code hangs
Definition at line 521 of file main.cpp.
References Hexapod::comms, and CommsManager::getMotorUART().
USART2_IRQHandler()
void USART2_IRQHandler (void)
UART2 (Remote) Handler.
Definition at line 528 of file main.cpp.
References Hexapod::comms, and CommsManager::getRemoteUART().
USART3_IRQHandler()
void USART3_IRQHandler (void)
UART3 (IMU) Handler.
Definition at line 537 of file main.cpp.
References Hexapod::comms, and CommsManager::getAccUART().
Variable Documentation
HEX
Hexapod HEX
Main Hexapod object.
Definition at line 20 of file main.cpp.